# In kubernetes we need to manually map the ports

apiVersion: v1
kind: Service # There are four types of services
metadata:
  name: client-node-port
spec:
  type: NodePort # One among the types of Node
  ports:
    - ports: 3050 # Use for other apps to connect to this application
      targetPort: 3000 # The traffic enters into tis port
      nodePort: 31515 # use for displaying the application on our local browser
  selector:
    component: web # referencing the pod name web
